name: Yarn upgrade

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, vite, vite-session ]
  schedule:
  - cron: '0 10 * 1-12 6'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: 'npm i -g yarn'
      - run: 'yarn upgrade'
  
  git-setup:
    runs-on: ubuntu-latest
    steps:
      - run: 'git config user.name "GitHub Actions Bot"'
      - run: 'git config user.email "<>"'
  
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - run: 'git add package.json yarn.lock'
      - run: 'git commit -m "Dependencies upgrade :arrow_up:"'
      - run: 'git push origin master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
