name: Yarn upgrade

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, vite, vite-session ]
  schedule:
  - cron: '0 10 * 1-12 6'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dependencies-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'update/yarn-upgrade'
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: 'Install Yarn'
        run: 'npm i -g yarn'
      - name: 'Dependencies upgrade'    
        run: 'yarn upgrade'
      - name: 'Git setup'
        run: 'git config --global user.name "GitHub Actions Bot" && git config --global user.email "<>"'
      - name: 'Stage changes'
        run: 'git add package.json yarn.lock'
      - name: 'Commit changes'
        run: 'git commit -m "Dependencies upgrade :arrow_up:"'
      - name: 'Push changes'
        run: 'git push origin update/yarn-upgrade'
 
  merge-master-branch:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0
      - name: 'Git setup'
        run: 'git config --global user.name "GitHub Actions Bot" && git config --global user.email "<>"'
      - name: 'Merge "update/yarn-upgrade" onto "master"'
        run: 'git merge update/yarn-upgrade'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
