name: Yarn upgrade
on:
  schedule:
  - cron: "0 10 * 1-12 6"
jobs:
  build:
    name: Yarn Upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: upgrade
